appname: "PhotoViewer"
layout: "main"
charset: "UTF-8"
template: "xslate"
engines:
  xslate:
    syntax: TTerse
    suffix: '.tt'
    cache: 1
    cache_dir: xslate_cache
plugins:
  DBIC:
    photo:
      schema_class: PhotoViewer::Schema
      dsn: "dbi:SQLite:dbname=data/photo.sqlite"
      options:
logger: file
log_path: logs
log_file: "PhotoViewer.log"
