appname: PhotoViewer
layout: main
charset: "UTF-8"
database: "data/photo.sqlite"
logger: file
log_path: logs
log_file: "PhotoViewer.log"
template: xslate
engines:
  template:
    xslate:
      syntax: TTerse
      suffix: .tt
      cache: 1
      cache_dir: xslate_cache
